language: node_js

node_js:
  - "stable"

os:
  - linux
  - osx

node_js:
  - "stable"

env:
  - AWS_ACCESS_KEY_ID=your-key-here
  - AWS_SECRET_ACCESS_KEY=your-secret-key-here

script:
  - npm run lint:all
  - npm run test:unit
  - npm run test:integration
  - npm run codecov
