service: demo

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}

functions:
  hello:
    handler: handler.hello

plugins:
  localPath: '../src'
  modules:
  - serverless-confirm-command

custom:
  confirm:
    commands:
      - 'deploy'
      - 'remove'
